// Generated by gencpp from file mcuserial_msgs/RequestParam.msg
// DO NOT EDIT!


#ifndef MCUSERIAL_MSGS_MESSAGE_REQUESTPARAM_H
#define MCUSERIAL_MSGS_MESSAGE_REQUESTPARAM_H

#include <ros/service_traits.h>


#include <mcuserial_msgs/RequestParamRequest.h>
#include <mcuserial_msgs/RequestParamResponse.h>


namespace mcuserial_msgs
{

struct RequestParam
{

typedef RequestParamRequest Request;
typedef RequestParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestParam
} // namespace mcuserial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcuserial_msgs::RequestParam > {
  static const char* value()
  {
    return "d7a0c2be00c9fd03cc69f2863de9c4d9";
  }

  static const char* value(const ::mcuserial_msgs::RequestParam&) { return value(); }
};

template<>
struct DataType< ::mcuserial_msgs::RequestParam > {
  static const char* value()
  {
    return "mcuserial_msgs/RequestParam";
  }

  static const char* value(const ::mcuserial_msgs::RequestParam&) { return value(); }
};


// service_traits::MD5Sum< ::mcuserial_msgs::RequestParamRequest> should match
// service_traits::MD5Sum< ::mcuserial_msgs::RequestParam >
template<>
struct MD5Sum< ::mcuserial_msgs::RequestParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcuserial_msgs::RequestParam >::value();
  }
  static const char* value(const ::mcuserial_msgs::RequestParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcuserial_msgs::RequestParamRequest> should match
// service_traits::DataType< ::mcuserial_msgs::RequestParam >
template<>
struct DataType< ::mcuserial_msgs::RequestParamRequest>
{
  static const char* value()
  {
    return DataType< ::mcuserial_msgs::RequestParam >::value();
  }
  static const char* value(const ::mcuserial_msgs::RequestParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcuserial_msgs::RequestParamResponse> should match
// service_traits::MD5Sum< ::mcuserial_msgs::RequestParam >
template<>
struct MD5Sum< ::mcuserial_msgs::RequestParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcuserial_msgs::RequestParam >::value();
  }
  static const char* value(const ::mcuserial_msgs::RequestParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcuserial_msgs::RequestParamResponse> should match
// service_traits::DataType< ::mcuserial_msgs::RequestParam >
template<>
struct DataType< ::mcuserial_msgs::RequestParamResponse>
{
  static const char* value()
  {
    return DataType< ::mcuserial_msgs::RequestParam >::value();
  }
  static const char* value(const ::mcuserial_msgs::RequestParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCUSERIAL_MSGS_MESSAGE_REQUESTPARAM_H
